# Generated by Django 6.0.6 on 2026-09-08 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('item_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Schedule'), ('ACCEPTED', 'Schedule Confirmed'), ('IN_PROGRESS', 'In Progress / Transit'), ('DELIVERED', 'Delivered / Handed Over'), ('COMPLETED', 'Completed & Impact Recorded'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACCEPTED', max_length=20)),
                ('scheduled_date', models.CharField(blank=True, default='Tomorrow, 10:00 AM', max_length=100)),
                ('pickup_time_slot', models.CharField(blank=True, default='10:00 AM - 12:00 PM', max_length=100)),
                ('pickup_address', models.CharField(blank=True, default='', max_length=255)),
                ('courier_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='donations.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_connections', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_connections', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='item_requests.donationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Pickup Scheduled'), ('PROCESSING', 'Processing'), ('TRANSIT', 'In Transit'), ('ARRIVING', 'Driver Arriving Soon'), ('DELIVERED', 'Delivered')], default='SCHEDULED', max_length=20)),
                ('courier_name', models.CharField(default='SecondLife Eco Courier', max_length=100)),
                ('courier_phone', models.CharField(default='+1 (555) 019-2831', max_length=50)),
                ('vehicle_info', models.CharField(default='Green Electric Van #SL-402', max_length=100)),
                ('estimated_arrival', models.CharField(default='Today, 2:30 PM - 4:00 PM', max_length=100)),
                ('timeline_steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='connections.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
