# Generated by Django 6.0.4 on 2026-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotfaq',
            options={'ordering': ['-priority', 'question']},
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('donations', 'Donations'), ('requests', 'Requests'), ('accounts', 'Accounts'), ('organizations', 'Organizations'), ('matching', 'Matching'), ('delivery', 'Delivery'), ('safety', 'Safety'), ('technical', 'Technical'), ('team', 'Team')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='keywords',
            field=models.TextField(blank=True, help_text='Separate keywords with commas. Example: donate, donation, give'),
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
