# Generated by Django 6.0.6 on 2026-09-08 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='package', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'New (In original packaging)'), ('LIKE_NEW', 'Like New (Barely used)'), ('GOOD', 'Good (Visible wear, fully functional)'), ('FAIR', 'Fair (Significant wear, needs minor repair)')], default='GOOD', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_option', models.CharField(choices=[('PICKUP', 'Pickup Available'), ('DELIVERY', 'Delivery Preferred'), ('EITHER', 'Pickup or Delivery')], default='PICKUP', max_length=20)),
                ('location', models.CharField(help_text='e.g. Ballard, Seattle, WA', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('PENDING', 'Pending Match'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('IN_DELIVERY', 'In Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='AVAILABLE', max_length=20)),
                ('dimensions', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.CharField(blank=True, default='', max_length=100)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.category')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donations.donation')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='donations.donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'category'], name='donations_d_status_6a52b9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['city', 'status'], name='donations_d_city_74fe1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('user', 'donation')},
        ),
    ]
